import logging
import uuid as uuidpkg
from datetime import datetime, timezone
from typing import Any, Sequence

from sqlalchemy import JSON, Column, DateTime, ForeignKey, Text
from sqlmodel import Field, SQLModel, select

from app.db import DBCtx

logger = logging.getLogger(__name__)


class Report(SQLModel, table=True):
    """Persisted report generated by the agent."""

    __tablename__ = "report"

    uuid: uuidpkg.UUID = Field(default_factory=uuidpkg.uuid4, primary_key=True)
    title: str = Field(default="")
    content: str = Field(default="", sa_column=Column(Text, nullable=False))
    report_type: str = Field(
        default="composite"
    )  # financial / sfa / document / composite
    summary: str | None = Field(default=None)
    metadata_json: Any = Field(default=None, sa_column=Column(JSON, nullable=True))
    user_uuid: uuidpkg.UUID = Field(
        sa_column=Column(
            "user_uuid",
            ForeignKey("user.uuid", ondelete="SET NULL"),
            nullable=True,
            index=True,
        )
    )
    chat_uuid: uuidpkg.UUID | None = Field(
        sa_column=Column(
            "chat_uuid",
            ForeignKey("chat.uuid", ondelete="SET NULL"),
            nullable=True,
        )
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


class ReportRepository:
    def __init__(self, db: DBCtx):
        self._db = db

    async def create_report(self, report: Report) -> Report:
        async with self._db.session(writable=True) as session:
            session.add(report)
            await session.commit()
            await session.refresh(report)
            return report

    async def get_report(self, uuid: uuidpkg.UUID) -> Report | None:
        async with self._db.session() as session:
            result = await session.exec(
                select(Report).where(Report.uuid == uuid).limit(1)
            )
            return result.one_or_none()

    async def list_reports(
        self,
        user_uuid: uuidpkg.UUID | None = None,
        report_type: str | None = None,
        limit: int = 50,
    ) -> Sequence[Report]:
        q = select(Report).order_by(Report.created_at.desc()).limit(limit)  # type: ignore[union-attr]
        if user_uuid:
            q = q.where(Report.user_uuid == user_uuid)
        if report_type:
            q = q.where(Report.report_type == report_type)
        async with self._db.session() as session:
            result = await session.exec(q)
            return result.all()

    async def delete_report(self, uuid: uuidpkg.UUID) -> bool:
        async with self._db.session(writable=True) as session:
            result = await session.exec(
                select(Report).where(Report.uuid == uuid).limit(1)
            )
            report = result.one_or_none()
            if not report:
                return False
            await session.delete(report)
            await session.commit()
            return True
